pipeline {
agent any

environment {
    AWS_REGION = 'us-east-1'
    ECR_REPO = '227655494308.dkr.ecr.us-east-1.amazonaws.com/order-tracking-app'
    IMAGE_TAG = "${BUILD_NUMBER}"
}

stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Build Docker Image') {
        steps {
            dir('app') {
                sh """
                docker build -t order-tracking-app:${IMAGE_TAG} .
                """
            }
        }
    }

    stage('Push To ECR') {
        steps {
            withCredentials([
                [$class: 'AmazonWebServicesCredentialsBinding',
                 credentialsId: 'aws-creds']
            ]) {
                sh """
                aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}

                docker tag order-tracking-app:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}

                docker push ${ECR_REPO}:${IMAGE_TAG}
                """
            }
        }
    }

    stage('Deploy To EKS') {
        steps {
            withCredentials([
                [$class: 'AmazonWebServicesCredentialsBinding',
                 credentialsId: 'aws-creds']
            ]) {
                sh """
                aws eks update-kubeconfig --region ${AWS_REGION} --name order-tracking-eks

                kubectl set image deployment/order-tracking-app order-tracking-app=${ECR_REPO}:${IMAGE_TAG}

                kubectl rollout status deployment/order-tracking-app

                kubectl get pods -o wide
                kubectl get svc
                """
            }
        }
    }
}

}