apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-tracking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-tracking-app
  template:
    metadata:
      labels:
        app: order-tracking-app
    spec:
      containers:
      - name: order-tracking-app
        image: 227655494308.dkr.ecr.us-east-1.amazonaws.com/order-tracking-app:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
